### ISSUE TITLE
스티커 저장

### ISSUE THREAD

**Issue by astrod** [happyhj/hogu-line-bot#5]
명령어를 저장한다.
ex)
@스티커 돼지 12345 54321

다음에 @스티커 돼지 하면 @StickerImg 12345 54321 처럼 동작하게 한다.

- firebase에 key : 다수의 value로 저장가능한지 확인할 필요 있음.
- 여러명이 돼지로 저장하면, 랜덤하게 그 중 하나를 리턴해서 보여준다.

**Comment by happyhj** [comment]
@stk.img 123123 123123 // 스티커 코드로 호출
@stk.add 돼지 123123 123123 // 스티커 키워드 등록
@stk 돼지 // 키워드로 스티커 호출
